import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import 'bootstrap/dist/css/bootstrap.min.css';
import AppNavBar from "./components/app.navbar";
import AppFooter from "./components/app.footer";
import { Container } from 'react-bootstrap';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ 
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column'
      }}>
          <AppNavBar />
          <main style={{ flex: 1 }}>
            <Container>
              {children}
            </Container>
          </main>
          <AppFooter />
      </body>
    </html>
  );
}
